
services:
  www:
    build: .
    ports:
      - "8888:80"
    volumes:
      - ./www:/var/www/html
    depends_on:
      - db
    networks:
      - lamp-network

  db:
    image: mysql:5.7
    ports:
      - "3307:3306"
    environment:
      MYSQL_DATABASE: dbname
      MYSQL_USER: test
      MYSQL_PASSWORD: test
      MYSQL_ROOT_PASSWORD: test
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - lamp-network

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    ports:
      - "8800:80"
    environment:
      PMA_HOST: db
      MYSQL_ROOT_PASSWORD: test
    depends_on:
      - db
    networks:
      - lamp-network

  adminer:
    image: adminer
    ports:
      - "8080:8080"
    depends_on:
      - db
    networks:
      - lamp-network

networks:
  lamp-network:

volumes:
  db_data:
